compraagendada/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url

from app.views.AdmView import *
from app.views.ClientView import *
from app.views.HomeView import *
from app.views.LoginView import *
from app.views.ProductView import *
from app.views.PainelView import PainelView
from app.views.BasketView import *
from app.views.ShowcaseView import *
from app.views.CartView import *
from app.views.PurchaseView import *
from app.views.SocialView import *

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^facebook/$', FacebookView.as_view(), name='facebook'),
    url(r'^twitter/$', TwitterView.as_view(), name='twitter'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(r'^register_client/$', RegisterClientView.as_view(), name='register_client'),
    url(r'^register_adm/$', RegisterAdmView.as_view(), name='register_adm'),
    url(r'^product/(?P<product_id>\d+)/$', ProductClientView.product_detail_client, name='product_client'),
    url(r'^basket/(?P<basket_id>\d+)/$', BasketView.basket_detail, name='basket_client'),
    url(r'^showcase_product/$', ShowcaseViewProduct.as_view(), name='showcase_products'),
    url(r'^showcase_basket/$', ShowcaseViewBasket.as_view(), name='showcase_baskets'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^account/$', DetailClientView.as_view(), name='detail'),
    url(r'^account/logout/$', LogoutView.as_view(), name='logout'),
    url(r'^account/edit_client/$', EditClientView.as_view(), name='edit_client'),
    url(r'^account/change_password_client/$', ChangePasswordClientView.as_view(), name='change_password_client'),
    url(r'^account/delete_client/$', delete_client, name='delete_client'),
    url(r'^account/purchases_historic/$', MyPurchaseListView.as_view(), name='purchases_historic'),
    url(r'^account/purchases_historic/purchase_(?P<pk>\d+)/$', DetailMyPurchaseView.as_view(), name='purchase'),
    url(r'^my_cart/$', EditCartView.as_view(), name='my_cart'),
    url(r'^my_cart/confirm_purchase/$', ShowCartView.as_view(), name='confirm_purchase'),
    url(r'^my_cart/confirm_purchase/buying/$', buying_view, name='buying'),
    url(r'^add_product/(?P<pk>\d+)/$', add_Product, name='add_product'),
    url(r'^add_basket/(?P<pk>\d+)/$', add_Basket, name='add_basket'),

    url(r'^painel/$', PainelView.as_view(), name='painel'),
    url(r'^painel/account/$', DetailAdmView.as_view(), name='detail_adm'),
    url(r'^painel/account/edit/$', EditAdmView.as_view(), name='edit_adm'),
    url(r'^painel/account/change_password_adm/$', ChangePasswordAdmView.as_view(), name='change_password_adm'),
    url(r'^painel/account/delete_adm/$', delete_adm, name='delete_adm'),
    url(r'painel/create_basketskel/$', CreateBasketSkelView.as_view(), name='create_basketskel'),
    url(r'painel/create_basket/$', CreateBasketView.as_view(), name='create_basket'),
    url(r'painel/auto_create_basket/$', AutoCreateBasketView.as_view(), name='auto_create_basket'),
    url(r'painel/basket_list/$', BasketListView.as_view(), name='basket_list'),
    url(r'painel/basketskel_list/$', BasketSkelListView.as_view(), name='basketskel_list'),
    url(r'painel/basket_list/(?P<basket_id>\d+)/$', BasketDetailView.basket_detail, name='basket_list_detail'),
    url(r'^painel/basket_list/edit_basket/(?P<pk>[0-9]+)/$', EditBasketView.as_view(), name='edit_basket'),
    url(r'^painel/new_product_type/$', NewProductTypeView.as_view(), name='new_product_type'),
    url(r'^painel/product_type_list/$', ProductTypeListView.as_view(), name='product_type_list'),
    url(r'^painel/delete_product_type/(?P<pk>\d+)/$', delete_product_type, name='delete_product_type'),
    url(r'^painel/register_product/$', RegisterProductView.as_view(), name='register_product'),
    url(r'^painel/product/(?P<product_id>\d+)/$',ProductView.product_detail, name='product'),
    url(r'^painel/product/edit_product/(?P<pk>[0-9]+)/$', EditProductView.as_view(), name='edit_product'),
    url(r'^painel/products/$', ProductListView.as_view(), name ='products'),
    url(r'^painel/products/removed/$', RemovedProductListView.as_view(), name ='removed_products'),
    url(r'^painel/delete_product/(?P<pk>[0-9]+)/$', delete_product, name ='delete_product'),
    url(r'^painel/delete_basket/(?P<pk>[0-9]+)/$', delete_basket, name ='delete_basket'),
    url(r'^painel/delete_basketskel/(?P<pk>[0-9]+)/$', delete_basketskel, name ='delete_basketskel'),
    url(r'^painel/register_purchases/$', RegisterPurchaseView.as_view(), name='register_purchase'),
    url(r'^painel/purchases/$', PurchaseListView.as_view(), name='list_purchases'),
    url(r'^painel/purchases/(?P<pk>[0-9]+)/$', EditPurchaseView.as_view(), name='purchase_cotrol'),



]

app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import MinValueValidator


# Create your models here.


class TimeStamped(models.Model):
    class Meta:
        abstract = True

    created_at = models.DateTimeField(auto_now_add=True)
    published_at = models.DateTimeField(auto_now=True)


class BaseAddress(models.Model):
    class Meta:
        abstract = True

    cep = models.CharField(max_length=15, blank=True)
    state = models.CharField(max_length=20, blank=True)
    city = models.CharField(max_length=100, blank=True)
    district = models.CharField(max_length=100, blank=True)
    address = models.CharField(max_length=100, blank=True)
    number = models.CharField(max_length=5, blank=True, null=True)
    complement = models.CharField(max_length=200, blank=True)


class Cart(models.Model):
    frete = models.FloatField(blank=True, default=0)

    class Meta:
        verbose_name = "Carrinho"
        verbose_name_plural = "Carrinhos"

    @property
    def total(self):
        acum = 0.0

        for cont in self.cartproduct_set.all():
            acum += cont.qnt * cont.product.price

        for cont in self.cartbasket_set.all():
            acum += cont.qnt * cont.basket.price

        if (self.frete != 0):
            acum += self.frete

        return float("%.2f" % acum)


class ServiceClient(TimeStamped, BaseAddress):
    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"

    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    phone = models.CharField(max_length=30, blank=True)
    cpf = models.CharField(max_length=100, blank=True, unique=True)
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE, unique=True, null=True)
    active = models.BooleanField(default=True)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if self._state.adding is True:
            self.cart = Cart.objects.create()
        super(ServiceClient, self).save(force_insert=force_insert, force_update=force_update,
                                        using=using, update_fields=update_fields)

    def delete(self, using=None, keep_parents=False):
        if self.active:
            self.active = False
            self.user.set_unusable_password()
            self.user.username = self.cpf
            self.user.save()
            self.save()

    def __unicode__(self):
        return u'%s %s' % (self.user.first_name, self.user.last_name)

    def __str__(self):
        return '%s %s' % (self.user.first_name, self.user.last_name)


class ItemManager(models.Manager):
    def get_queryset(self):
        return super(ItemManager, self).get_queryset().filter(available=True)


class Item(models.Model):
    class Meta:
        abstract = True

    name = models.CharField(max_length=300)
    cost = models.FloatField(blank=True, default=0)
    profit = models.FloatField(blank=True, default=0)
    photo = models.URLField(blank=True, null=True)
    stock = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    available = models.BooleanField(default=True)
    sold = models.IntegerField(default=0, validators=[MinValueValidator(0)])

    objects = ItemManager()
    all_objects = models.Manager()

    def delete(self, using=None, keep_parents=False):
        if self.available:
            self.available = False
            self.stock = 0
            self.save()

    @property
    def price(self):
        real_price = self.cost + (self.cost * self.profit)
        return float("%.2f" % real_price)

    @property
    def stock_state(self):
        if self.stock > 10:
            return "Em Estoque"
        elif self.stock == 0:
            return "Esgotado"
        else:
            return "Ultimas Unidades"


class ServiceAdm(TimeStamped):
    class Meta:
        verbose_name = "Administrador"
        verbose_name_plural = "Administradores"

    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    phone = models.CharField(max_length=30, blank=True)

    def __unicode__(self):
        return u'%s' % self.user.first_name

    def __str__(self):
        return self.user.first_name


class ProductType(models.Model):
    class Meta:
        verbose_name = "Tipo de Produto"
        verbose_name_plural = "Tipos de Produto"
        ordering = ['name']

    name = models.CharField(max_length=50, unique=True)

    def __unicode__(self):
        return u'%s' % self.name

    def __str__(self):
        return self.name


class BasketSkel(TimeStamped):
    class Meta:
        verbose_name = "Estrutura de Cesta"
        verbose_name_plural = "Estruturas de Cesta"

    name = models.CharField(max_length=300)

    def __unicode__(self):
        return u'%s' % self.name

    def __str__(self):
        return self.name


class ContentQnt(models.Model):
    basketskel = models.ForeignKey(to=BasketSkel, on_delete=models.CASCADE)
    type = models.ForeignKey(ProductType, on_delete=models.PROTECT)
    qnt = models.IntegerField()

    def __unicode__(self):
        return u'x%d %s' % (self.qnt, str(self.type))

    def __str__(self):
        return 'x%d %s' % (self.qnt, str(self.type))


class Product(TimeStamped, Item):
    class Meta:
        verbose_name = "Produto"
        verbose_name_plural = "Produtos"

    brand = models.CharField(max_length=100)
    distributor = models.CharField(max_length=100)
    type = models.ForeignKey(ProductType, on_delete=models.PROTECT)

    def __unicode__(self):
        return u'%s %s - R$ %.2f' % (self.name, self.brand, self.cost)

    def __str__(self):
        return '%s %s - R$ %.2f' % (self.name, self.brand, self.cost)


class Basket(TimeStamped, Item):
    class Meta:
        verbose_name = "Cesta"
        verbose_name_plural = "Cestas"

    def __unicode__(self):
        return u'%s' % self.name

    def __str__(self):
        return self.name


class BasketContent(models.Model):
    basket = models.ForeignKey(to=Basket, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    qnt = models.IntegerField(validators=[MinValueValidator(1)])

    def __unicode__(self):
        return u'x%d %s' % (self.qnt, str(self.product))

    def __str__(self):
        return 'x%d %s' % (self.qnt, str(self.product))


class CartProduct(models.Model):
    cart = models.ForeignKey(to=Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    qnt = models.IntegerField(default=1, validators=[MinValueValidator(1)])

    def __unicode__(self):
        return u'x%d %s' % (self.qnt, self.product.name)

    def __str__(self):
        return 'x%d %s' % (self.qnt, self.product.name)


class CartBasket(models.Model):
    cart = models.ForeignKey(to=Cart, on_delete=models.CASCADE)
    basket = models.ForeignKey(Basket, on_delete=models.PROTECT)
    qnt = models.IntegerField(default=1, validators=[MinValueValidator(1)])

    def __unicode__(self):
        return u'x%d %s' % (self.qnt, self.basket.name)

    def __str__(self):
        return 'x%d %s' % (self.qnt, self.basket.name)


purchase_status = (
    ("IN_PROGRESS", "Em Andamento"),
    ("AWAITING_PAYMENT", "Aguardando Pagamento"),
    ("COMPLETED", "Concluida"),
    ("CANCELED", "Cancelada"),
)


class Purchase(TimeStamped):
    class Meta:
        verbose_name = "Compra"
        verbose_name_plural = "Compras"

    client = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=purchase_status, default="IN_PROGRESS")
    frete_value = models.FloatField(blank=True, default=0)

    @property
    def total(self):
        acum = 0.0

        for cont in self.purchaseproduct_set.all():
            acum += cont.qnt * cont.price

        for cont in self.purchasebasket_set.all():
            acum += cont.qnt * cont.price


        acum += self.client.serviceclient.cart.frete
        self.frete_value = self.client.serviceclient.cart.frete

        return float("%.2f" % acum)



class PurchaseProduct(models.Model):
    purchase = models.ForeignKey(to=Purchase, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    qnt = models.IntegerField(default=1, validators=[MinValueValidator(1)])
    price = models.FloatField(blank=True, default=0)

    def __unicode__(self):
        return u'x%d %s - %.2f' % (self.qnt, self.product.name, (self.qnt * self.price))

    def __str__(self):
        return 'x%d %s - %.2f' % (self.qnt, self.product.name, (self.qnt * self.price))

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.price = self.product.price
        super(PurchaseProduct, self).save(force_insert=force_insert, force_update=force_update,
                                          using=using, update_fields=update_fields)


class PurchaseBasket(models.Model):
    purchase = models.ForeignKey(to=Purchase, on_delete=models.CASCADE)
    basket = models.ForeignKey(Basket, on_delete=models.PROTECT)
    qnt = models.IntegerField(default=1, validators=[MinValueValidator(1)])
    price = models.FloatField(blank=True, default=0)

    def __unicode__(self):
        return u'x%d %s - %.2f' % (self.qnt, self.basket.name, (self.qnt * self.price))

    def __str__(self):
        return 'x%d %s - %.2f' % (self.qnt, self.basket.name, (self.qnt * self.price))

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.price = self.basket.price
        super(PurchaseBasket, self).save(force_insert=force_insert, force_update=force_update,
                                         using=using, update_fields=update_fields)

templates/login-files/AutoCreateBasket.html
{% extends 'login-files/PainelBase.html' %}
{% load staticfiles %}

{% block content %}

    <form method="post" class="form-horizontal" data-parsley-validate="">
        {% csrf_token %}
        <fieldset>

            <!-- Form Name -->
            <div class="panel panel-default">
                <div class="panel-heading" style="text-align: center">
                    <h3 class="panel-title">
                        <strong><i class="fa fa-cog"></i> Gerar Cesta</strong>
                    </h3>
                    <p >Escolha uma Estrutura de Cesta para gerar automaticamente uma
                        Cesta contendo os produtos de menor custo a partir da estrutura selecionada.</p>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label" for="nome">Estrutura da Cesta</label>
                <div class="col-md-4">
                    {{ form.basketskel }}

                </div>
            </div>


            <div class="form-group">
                <label class="col-md-4 control-label" for="marca">Lucro</label>
                <div class="col-md-4">
                    {{ form.profit }}

                </div>
            </div>


            <div class="form-group">
                <label class="col-sm-2 col-form-label" for="foto" style="padding-right: 0">Foto</label>
                <div class="col-md-8" >
                    {{ form.file}}

                </div>
            </div>

            <!-- Button -->
            <div class="form-group">
                <div class="col-md-8 col-md-offset-3">
                    <div class="row">
                        <div class="col-sm-4">
                            <button id="btn_salvar" name="submit" class="btn btn-success btn-block" type="submit">
                                Criar
                            </button>
                        </div>
                        <div class="col-sm-4">
                            <a href="{% url "painel" %}" id="btn_cancelar" class="btn btn-danger btn-block">Cancelar</a>
                        </div>
                    </div>
                </div>
            </div>

        </fieldset>
    </form>

{% endblock %}

templates/login-files/BasketDetail.html
{% extends 'login-files/PainelBase.html' %}
{% load staticfiles %}

{% block content %}


    <div class="treasure panel panel-default">

        <div class="panel-heading">
            <h3 class="panel-title" align="center">{{ basket.name }}</h3>
        </div>

        <div class="panel-body">
            <center>
                <div class="form-group">
                    <label for="exampleInputPassword1"> </label>
                    <img src="{{ basket.photo }}" class="img-responsive" height="160" width="160"/>
                </div>
            </center>
            <table class="treasure-table" align="center">
                <tr>
                    <th>
                        Custo:
                    </th>
                    <td>R$ {{ basket.cost }}</td>
                </tr>
                <tr>
                    <th>
                        Preço:
                    </th>
                    <td>R$ {{ basket.price }}</td>
                </tr>
                <tr>
                    <th>
                        Lucro:
                    </th>
                    <td>{{ basket.profit }}</td>
                </tr>
                <tr>
                    <th>
                        Estoque:
                    </th>
                    <td>{{ basket.stock }}</td>
                </tr>

            </table>
        </div>

        <div class="treasure panel panel-default">

            <div class="panel-heading">
                <h3 class="panel-title" align="center">Produtos Incluidos </h3>
                <b></b>
                <div></div>
            </div>
            <div class="panel-body">
                {% for basketcontent in basket.basketcontent_set.all %}
                    <tr>
                        <div class="col-md-4">
                            <div class="treasure panel panel-default">
                                <!-- Adding treasure title by username -->
                                <div class="panel-heading">
                                    <h3 class="panel-title" align="center">{{ basketcontent.product.name }}</h3>
                                </div>
                                <!-- Adding treasure image -->
                                <div class="panel-body" align="center">
                                    <a href="/painel/product/{{ basketcontent.product.id }}">
                                        <div class="treasure-photo">
                                            <img src="{{ basketcontent.product.photo }}" height="160" width="160">
                                        </div>
                                    </a>
                                    <!-- Adding Like Button -->

                                </div>
                                <div align="center">
                                    R$ {{ basketcontent.product.price }}
                                </div>
                                <div align="center">
                                    Quantidade: {{ basketcontent.qnt }}
                                </div>

                            </div>
                        </div>
                    </tr>
                {% endfor %}

            </div>
        </div>

        <div class="row">
            <div class="center-block" style="width:300px">
                <a href="{% url 'edit_basket' basket.pk %}" id="btn_edit"
                   class="btn btn-default center-block" type="submit">
                    <i class="fas fa-pencil-alt"></i> Editar
                </a>
            </div>
            <div class="center-block" style="width:300px">
                <a href="{% url "basket_list" %}" id="btn_cancelar"
                   class="btn btn-danger center-block btn-block" type="submit">
                    <i class="fas fa-chevron-left"></i> Voltar
                </a>
            </div>
        </div>
        <div class="row">
            <br>
            <div class="col-md-4 pull-right" style="width:160px">
                <a href="{% url 'delete_basket' basket.pk %}" id="btn_del" class="btn btn-default btn-block pull-right">
                    <i class="fa fa-trash" style="color: #dd000b"></i> Deletar Cesta
                </a>
            </div>
        </div>


    </div>
{% endblock %}

templates/login-files/BasketList.html
{% extends 'login-files/PainelBase.html' %}
{% load staticfiles %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <!-- /.box-header -->
                <div class="box-header">
                </div>
                <!-- /.box-body -->
                <div class="box-body">
                    <div class="dataTables_wrapper form-inline dt-bootstrap" id="example1_wrapper">
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="table" class="table table-bordered table-striped" class="display"
                                       cellspacing="0" width="100%">
                                    <thead>
                                    <tr>
                                        <th>NOME</th>
                                        <th>CUSTO</th>
                                        <th>PREÇO</th>
                                        <th>LUCRO</th>
                                        <th>ESTOQUE</th>>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for basket in baskets %}
                                        <tr>
                                            <td><a href="/painel/basket_list/{{ basket.id }}">{{ basket }}</a></td>
                                            <td>R$ {{ basket.cost }}</td>
                                            <td>R$ {{ basket.price }}</td>
                                            <td>{{ basket.profit }}</td>
                                            <td>{{ basket.stock }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
                {% if user.is_superuser %}
                    <div class="box-footer">
                        <a href="{% url 'painel' %}" class="btn btn-default pull-left">Voltar</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#list_basket').addClass('active');
        });
    </script>

{% endblock %}

templates/login-files/BasketSkelList.html
{% extends 'login-files/PainelBase.html' %}
{% load staticfiles %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <!-- /.box-header -->
                <div class="box-header">
                </div>
                <!-- /.box-body -->
                <div class="box-body">
                    <div class="dataTables_wrapper form-inline dt-bootstrap" id="example1_wrapper">
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="table" class="table table-bordered table-striped" class="display"
                                       cellspacing="0" width="100%">
                                    <thead>
                                    <tr>
                                        <th>NOME</th>
                                        <th>CONTEUDO</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for basketskel in basketskels %}
                                        <tr>
                                            <td>{{ basketskel }}</td>
                                            <td>{% for cont in basketskel.contentqnt_set.all %}
                                                <ul>{{ cont }}</ul>
                                                {% endfor %}
                                            </td>
                                            <td>
                                                <div class="col-md-4 pull-right" style="width:80px">
                                                    <a href="{% url 'delete_basketskel' basketskel.pk %}" id="btn_del" class="btn btn-default btn-block pull-right">
                                                        <i class="fa fa-trash" style="color: #dd000b"></i>
                                                    </a>
                                                </div>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
                {% if user.is_superuser %}
                    <div class="box-footer">
                        <a href="{% url 'painel' %}" class="btn btn-default pull-left">Voltar</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#list_basketskel').addClass('active');
        });
    </script>

{% endblock %}

templates/login-files/CreateBasketSkel.html
{% extends 'login-files/PainelBase.html' %}
{% load staticfiles %}

{% block content %}

    <form method="post" class="form-horizontal" data-parsley-validate="">
        {% csrf_token %}
        <fieldset>

            <!-- Form Name -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <center>Criar Estrutura de Cesta</center>
                    </h3>
                </div>
            </div>

             <div class="form-group">
                <div class="col-md-8 col-md-offset-3">
                    {{ form.as_p }}
                </div>
            </div>

            <!-- Button -->
            <div class="form-group">
                <div class="col-md-8 col-md-offset-3">
                    <div class="row">
                        <div class="col-sm-4">
                            <button id="btn_salvar" name="submit" class="btn btn-success btn-block" type="submit">
                                Criar
                            </button>
                        </div>
                        <div class="col-sm-4">
                            <a href="{% url "painel" %}" id="btn_cancelar" class="btn btn-danger btn-block">Cancelar</a>
                        </div>
                    </div>
                </div>
            </div>

        </fieldset>
    </form>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#new_basketskel').addClass('active');
        });
    </script>

{% endblock %}

templates/login-files/PurchaseList.html
{% extends 'login-files/PainelBase.html' %}
{% load staticfiles %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <!-- /.box-header -->
                <div class="box-header">
                </div>
                <!-- /.box-body -->
                <div class="box-body">
                    <div class="dataTables_wrapper form-inline dt-bootstrap" id="example1_wrapper">
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="table" class="table table-bordered table-striped" class="display"
                                       cellspacing="0" width="100%">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>COMPRADOR</th>
                                        <th>DATA</th>
                                        <th>VALOR TOTAL</th>
                                        <th>SITUAÇÃO</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                        {% for purchase in purchases %}
                                            <tr>
                                                <td><a href="{% url 'purchase_cotrol' purchase.pk %}">
                                                    {{ purchase.id }}</a></td>
                                                <td>{{ purchase.client.serviceclient }}</td>
                                                <td>{{ purchase.created_at }}</td>
                                                <td>R$ {{ purchase.total }}</td>
                                                <td>{% if purchase.status == "IN_PROGRESS" %}
                                                        <label class="label label-warning">
                                                    {% elif purchase.status == "AWAITING_PAYMENT" %}
                                                        <label class="label label-info">
                                                    {% elif purchase.status == "CANCELED" %}
                                                        <label class="label label-danger">
                                                    {% else %}
                                                        <label class="label label-success">
                                                    {% endif %}
                                                            {{ purchase.get_status_display }}
                                                        </label>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
                {% if user.is_superuser %}
                    <div class="box-footer">
                        <a href="{% url 'painel' %}" class="btn btn-default pull-left">Voltar</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#list_purchase').addClass('active');
        });
    </script>

{% endblock %}